// Create a function to generate markdown for README
function generateReadme(answers) {
  return `
<h1 align="center">${answers.projectTitle} </h1>
  
## Description
  ${answers.description}
## Table of Contents
- [Description](#description)
- [Installation](#installation)
- [Usage](#usage)
- [License](#license)
- [Contributors](#contributing)
- [Tests](#tests)
- [Questions](#questions)
## Installation
  ${answers.installation}
## Usage
  ${answers.usage}
## License
This application is covered by the ${answers.license} license. 
## Contributors
  ${answers.contributing}
## Tests
  ${answers.tests}
## Questions
  ${answers.questions}<br />
<br />
Find me on GitHub: [${answers.username}](https://github.com/${answers.username})<br />
<br />
  Email me with any questions: ${answers.email}<br /><br />
_This README was generated by [ReadMe-generator](https://github.com/AbrahamBarajas13/09-ReadMeGenerator)_
    `;
  }

module.exports = generateReadme;
